### ISSUE TITLE
外行看不懂怎么用啊，求老哥指路

### ISSUE THREAD

**Issue by CarlRyou** [xieyumc/YuYuWechatV2#1]
我是个小白，没有exe真的完全不知道怎么搞，当然我知道让老哥你手把手教我是不太可能的，能不能至少告诉我哪里有教程😭，我真的很需要这个功能
![QQ20241005-213529](https://github.com/user-attachments/assets/39fc0122-1179-4632-9329-d5c3a175011b)

**Comment by xieyumc** [comment]
https://github.com/xieyumc/YuYuWechat
 
 访问这个，本仓库已经不更新了
